workflows:
  ios-unsigned:
    name: iOS Unsigned Build
    instance_type: mac_m1
    environment:
      flutter: stable
      xcode: latest
    scripts:
      - name: Get Flutter Dependencies
        script: flutter pub get
      - name: Build iOS (Unsigned)
        script: flutter build ios --no-codesign
    artifacts:
      - build/ios/iphoneos/*.app
      - build/ios/iphoneos/*.ipa