workflows:
  ios-build:
    name: iOS Build
    environment:
      flutter: stable
      xcode: latest
    scripts:
      - name: Debug directory
        script: |
          echo "Current directory:"
          pwd
          echo "Files:"
          ls -la
      - name: Get dependencies
        script: flutter pub get
      - name: Create exportOptions.plist
        script: |
          cat > ios/exportOptions.plist <<EOF
          <?xml version="1.0" encoding="UTF-8"?>
          <!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
          <plist version="1.0">
          <dict>
              <key>method</key>
              <string>ad-hoc</string>
              <key>signingStyle</key>
              <string>manual</string>
              <key>stripSwiftSymbols</key>
              <true/>
              <key>compileBitcode</key>
              <false/>
              <key>destination</key>
              <string>export</string>
              <key>manageAppVersionAndBuildNumber</key>
              <false/>
          </dict>
          </plist>
          EOF
      - name: Build iOS IPA
        script: flutter build ipa --export-options-plist=ios/exportOptions.plist
    artifacts:
      - build/ios/ipa/*.ipa
