workflows:
  ios-build:
    name: iOS Build
    environment:
      flutter: stable
      xcode: latest
      os: macos
    scripts:
      - name: Get dependencies
        script: flutter pub get
      - name: Build iOS app (no code signing)
        script: flutter build ios --release --no-codesign
      - name: Archive with xcodebuild
        script: |
          xcodebuild -workspace ios/Runner.xcworkspace \
          -scheme Runner \
          -configuration Release \
          -archivePath $PWD/build/Runner.xcarchive archive
      - name: Export IPA
        script: |
          xcodebuild -exportArchive \
          -archivePath $PWD/build/Runner.xcarchive \
          -exportPath $PWD/build/ios/ipa \
          -exportOptionsPlist ios/exportOptions.plist
    artifacts:
      - build/ios/ipa/*.ipa
