workflows:
  android-build:
    name: Android Build
    max_build_duration: 60
    environment:
      vars:
        JAVA_TOOL_OPTIONS: "-Xmx4g"
      flutter: stable
    scripts:
      - name: Build APK
        script: |
          flutter pub get
          flutter build apk --debug
    artifacts:
      - build/app/outputs/flutter-apk/app-debug.apk